# Generated by Django 4.2.5 on 2023-09-21 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HQapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlesson',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='productlesson',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(related_name='included_in_products', to='HQapp.lesson'),
        ),
        migrations.AddField(
            model_name='product',
            name='users_with_access',
            field=models.ManyToManyField(related_name='accessible_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.DeleteModel(
            name='ProductLesson',
        ),
    ]
